server:
  port: 8081

spring:
  profiles:
    active: default
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/taekwondo
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secretKey: "cQKwXc7ABbVUjmjBHwc/6Hql9guJAlhRyPQ8Esr/av6WpVuwiMg5zb+Hh8zQHZ6AVdAUh8onqA5C4vJkPJqsFcZXUIQtIyOzwwQ/ESXIN3I="

